### ISSUE TITLE
Total reward different to exported transaction history

### ISSUE THREAD

**Issue by friedger** [fungible-systems/stacking-club#1]
For cycle 11, I exported the transaction history of 33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq the reward address of Friedger Pool e.g. https://www.walletexplorer.com/address/33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq and compared it with the total of https://stacking.club/reward-address/33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq/11

I compared the timestamp of the last reward on stacking club for cycle 10 ([#688825](https://stacking.club/reward-address/33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq/10)) and 11 ([#690955](https://stacking.club/reward-address/33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq/11)) and added the transaction values between these dates: 2021-06-29 23:45:12 and 2021-07-14 09:20:18 (minus payout on 2021-07-13 23:25:32). Considering time zone differences.

The total of the exported txs is 1.16474
The total of stacking club is 1.211345

Which total is the correct stacking reward for that address for cycle 11?

[walletexplorer-33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq-1.csv](https://github.com/fungible-systems/stacking-club/files/6820896/walletexplorer-33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq-1.csv)

**Comment by aulneau** [comment]
yep -- Plan better reached out to me yesterday to report something similar -- it seems from my looking into it that the endpoint I use to generate the reports for reward payments `https://stacks-node-api.mainnet.stacks.co/extended/v1/burnchain/rewards` isn't as static as I thought, and so it's possible that rewards change their index or other value and my importer will duplicate import certain rewards. I am working on a script that will run at certain times to ensure there are no orphan or duplicate rewards -- will report back when it has run to confirm numbers.

**Comment by aulneau** [comment]
This has been resolved!
